// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7M_jZnS-ex0qypeHQjvYBeQOCOhsr2rQ',
    appId: '1:470114617428:web:7b9b23eeaec4beefe845c1',
    messagingSenderId: '470114617428',
    projectId: 'qutter-eeb9f',
    authDomain: 'qutter-eeb9f.firebaseapp.com',
    storageBucket: 'qutter-eeb9f.appspot.com',
    measurementId: 'G-Q830T09JPG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlDv2Te5nyGPPk0F5rcTXL1L2-CYuFyzE',
    appId: '1:470114617428:android:82da675ffaf9d176e845c1',
    messagingSenderId: '470114617428',
    projectId: 'qutter-eeb9f',
    storageBucket: 'qutter-eeb9f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDW3ZKmjqEGErlDoh6zIn8r55ISfYBduFk',
    appId: '1:470114617428:ios:25dcacad2b1ce874e845c1',
    messagingSenderId: '470114617428',
    projectId: 'qutter-eeb9f',
    storageBucket: 'qutter-eeb9f.appspot.com',
    iosBundleId: 'com.example.quetter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDW3ZKmjqEGErlDoh6zIn8r55ISfYBduFk',
    appId: '1:470114617428:ios:3f8093b34e1944d6e845c1',
    messagingSenderId: '470114617428',
    projectId: 'qutter-eeb9f',
    storageBucket: 'qutter-eeb9f.appspot.com',
    iosBundleId: 'com.example.quetter.RunnerTests',
  );
}
